version: "3.0"
services:

  backend:
    image: git-stats-backend:1.0-SNAPSHOT
    ports:
      - "9000:9000"
    volumes:
      - ~/.ssh:/root/.ssh
      - ~/.git-stats-tasks:/root/.tasks
      - ./conf/tags:/root/tags

  db:
    image: mysql:5.7
    ports:
      - "3307:3306"
    environment:
    - MYSQL_ROOT_PASSWORD=1q2w3e4r5t
    - LANG=en_US.UTF-8
    tmpfs:
    - /tmp

